### ISSUE TITLE
Polish letter "ł" kerning too tight?

### ISSUE THREAD

**Issue by tszynalski** [erikdkennedy/figtree#10]
I took it for a spin and it looks like the keming is weird in the word "żółty" (yellow). To my eye, the letter "ł" is too close to neighboring letters, especially compared to the distance between "ż" and "ó".

**Comment by erikdkennedy** [comment]
Thanks! Can you post an image of this letter with better kerning? Or recommend a font that does a good job with it? I will investigate 🙂

**Comment by tszynalski** [comment]
I think Lato does it better (maybe because it was made by a Pole). Open Sans seems to have a similar issue.

![image](https://user-images.githubusercontent.com/868003/192894037-0eb408f3-309b-4504-96ab-5f29ca0c1fd2.png)

**Comment by erikdkennedy** [comment]
Hm, many fonts keep that letter pretty tight. Nonetheless, I did add some space. My goal is to keep the general feel of whitespace between glyphs equal. For those that that have a "pointy" part of the character (such as ł), the glyph will get closer to neighboring characters. Does this read a bit better though?
<img width="499" alt="Screen Shot 2022-10-04 at 10 25 53 AM" src="https://user-images.githubusercontent.com/3440839/193885950-d99f7fca-e553-44c1-83d3-335f890096d7.png">

**Comment by tszynalski** [comment]
Looks better, but I think part of the issue is the distance between ż and ó. Don't you feel that ż feels separated from the rest of the word?
