### ISSUE TITLE
wrong german quotation mark

### ISSUE THREAD

**Issue by eiswurm** [erikdkennedy/figtree#11]
The german quotion mark (&bdquo;) has just one line, while it should have two.

**Comment by erikdkennedy** [comment]
Thanks – fixed!
<img width="423" alt="Screen Shot 2022-10-04 at 10 35 18 AM" src="https://user-images.githubusercontent.com/3440839/193887755-247da1fc-1419-4c08-a506-345cfe8215df.png">
