### ISSUE TITLE
The lowercase eth needs some looking at

### ISSUE THREAD

**Issue by bofs-is** [erikdkennedy/figtree#12]
The lowercase eth in the tyepface needs a rework, on this site you can find a guide on how to do it:
https://sites.google.com/view/briem/type-design/thorn-and-eth

**Comment by erikdkennedy** [comment]
Thanks for the heads up here. Fixed in latest commit 👍
<img width="410" alt="image" src="https://user-images.githubusercontent.com/3440839/193867034-486aecc2-4572-40eb-b141-8b9b18d0a8d5.png">
