### ISSUE TITLE
Adding Indian INR rupee symbol

### ISSUE THREAD

**Issue by manishjainn** [erikdkennedy/figtree#18]
The moment we say this font, immediately fall in love with it. We think it's one of the best font that Google as ever had. In terms of ascenders, decenders, line height and font weights its balance and looks beautiful. Great work Erik. 

We have a small request, if you can add an Indian rupee symbol to it. This solves our lots of issues which is resisting us to use this family as our daily driver in India.

**Comment by manishjainn** [comment]
Hi Eric,
Did you get a chance to work on the Rupee "₹" symbol.

**Comment by erikdkennedy** [comment]
Done! Please see newest release.

(Note: I will not re-submit to Google Fonts until there are more substantial changes as well)

**Comment by manishjainn** [comment]
Thanks Eric. It's working flawlessly. You have a good soul and do listen to people request. A true designer with empathy.

Really appreciate for the efforts. Thanks once again :)

> Done! Please see newest release.
> 
> (Note: I will not re-submit to Google Fonts until there are more substantial changes as well)
