### ISSUE TITLE
Add alternative coma, semicolon, quotation mark styles

### ISSUE THREAD

**Issue by Jat2021** [erikdkennedy/figtree#21]
It would be great if there would be an alternative style of those quotation marks with the traditional hooks on them other than the current geometric ones. (And perhaps a squared ones too like those of Gotham?)

P.S. I am using the font for my personal Front-end Developer portfolio currently in the layout process.

Thank you

**Comment by erikdkennedy** [comment]
Nice! I will keep this in mind relative to other requests and ideas for the font, but my gut reaction is: _not happening anytime soon_. The accents and punctuation aligning with baseline/cap-height feels like a somewhat central design decision to the font – even wrote about it here: https://erikdkennedy.com/projects/figtree.html.

**Comment by rben01** [comment]
I agree, I tend to prefer the dot+hook style for commas and quotation marks to the wedge style.
