### ISSUE TITLE
Variable version renders unevenly

### ISSUE THREAD

**Issue by tillsanders** [erikdkennedy/figtree#23]
I started playing with Figtree using the variable version. I quickly noticed that there are rendering issues, at least in some characters. I would see a tiny bump that would vanish when I zoomed in. It looked like a quality issue so I nearly gave up. Because the font is an excellent replacement for Avenir Next though, I decided to compare the result to the non-variable version. As you can see in the screenshot below, it renders differently. 

<img width="1726" src="https://user-images.githubusercontent.com/1533846/220144933-b84ecd5e-e3e3-46d4-8e4c-a681e4eab5be.png">

The variable version is on the left, the normal version on the right.
Notice the additional antialiasing pixels at the top? They don't exist in the non-variable version.
I'm not sure if this is a problem inherent to variable fonts that I was unaware of or if something can be done about it.

**Comment by erikdkennedy** [comment]
This aliasing stuff is still above my paygrade, to be honest.

@emmamarichal is there someone I should tag, or some other place to open this bug that makes more sense?

**Comment by tillsanders** [comment]
I can only assume this might happen because the curves overlap there. But this is always tricky business and I have no experience with developing fonts, so... I just wanted to point it out.

**Comment by tillsanders** [comment]
Very interesting! Thank you ❤️

**Comment by erikdkennedy** [comment]
This should be fixed with today's changes 👍
