### ISSUE TITLE
Having standard lowercase 'a' in italic

### ISSUE THREAD

**Issue by Walven** [erikdkennedy/figtree#28]
Hey!

I noticed that the italic version of the font only had the single-storey a, whereas the normal version has this 'a' in its stylistic sets. 

It's quite strange to see these 'a's change when you switch to italic.

**Comment by erikdkennedy** [comment]
FWIW, it's not that uncommon 🤷‍♂️ (since the double-storey 'a' is such a dense letterform, it's a bit more awkward when italicized).

If you end up trying a double-storey italic 'a' for Oak, here's my quickstart guide 😉:
https://github.com/erikdkennedy/figtree/pull/15#issuecomment-1509363825
