### ISSUE TITLE
Indian '₹' Rupee symbol not working on v2.0.3

### ISSUE THREAD

**Issue by kaushalswarup** [erikdkennedy/figtree#32]
The '₹' rupee symbol that was added in v2.0.1 isn't working anymore in the latest 2.0.3 version

**Comment by erikdkennedy** [comment]
Very weird. I've fixed and re-committed, which you can download here: https://github.com/erikdkennedy/figtree/tree/master/fonts

I don't know a good way of combing the source code over time to find how/where this went wrong, but let me know if it happens again, I will figure out what's causing this.
