### ISSUE TITLE
Adding ligatures

### ISSUE THREAD

**Issue by maticbroz** [erikdkennedy/figtree#33]
Are there any plans to add ligatures? It's such a nice font, but "ff" is soooo far apart.

**Comment by inferno986return** [comment]
@erikdkennedy closed my request for ligatures, so I doubt it: https://github.com/erikdkennedy/figtree/issues/19

I suppose kerning/tracking could be adjusted for the 2 glyph instead?

**Comment by erikdkennedy** [comment]
Yup, from #19:

> Figtree doesn't have fi-ff-ffi-fl ligatures and I don't have any plans to add them.
> (For context, many geometric sans serifs do away with these, and I don't see them as being of particular value. Worth noting that for Figtree, they'd be an especially big change, since the font name contains an "fi"!)
