### ISSUE TITLE
Different Names for Static and Variable Fonts

### ISSUE THREAD

**Issue by JohJakob** [erikdkennedy/figtree#39]
Currently, both the static and the variable fonts have the same name. This leads to Font Book on macOS and other applications (e.g., Figma) not recognising them as different fonts and unexpected results when using Figtree.

![Font Book](https://github.com/erikdkennedy/figtree/assets/9888537/cafc144a-375a-4f71-bbfd-d8de400f689d)

I suggest giving the variable fonts a different name such as “Figtree Variable” or “Figtree V”.

**Comment by erikdkennedy** [comment]
I believe Google Fonts format requires me to have it as is. @emmamarichal, is this true?

But either way, what happens if you simply choose to keep both? Does it work as expected in your apps, or are there issues?

**Comment by emmamarichal** [comment]
Hello @JohJakob!
We build the statics from the variable font, that why they have the same name. But in the variable version, you will find the same styles available, and it shouldn't make any difference.
We can't change the font name, to avoid having two Figtree versions on Google Fonts (one variable, and the other not).

Don't hesitate if you have other questions!

Cheers!

**Comment by JohJakob** [comment]
It appears to work fine in Figma for example, but the Affinity apps have trouble when both variants are installed. They show all weights twice (see screenshot). Since the Affinity apps do not support variable fonts (yet), I would like to have the static fonts present as well.

![Affinity Designer Font Weight Dropdown](https://github.com/erikdkennedy/figtree/assets/9888537/5584219e-c63c-4f00-8608-f9bf5383e211)

I understand the name limitation to support Google Fonts. I guess I can just export them with different names from Glyphs myself.

**Comment by emmamarichal** [comment]
Ah yes I see! But on affinity, why do you not only install the static versions?

**Comment by JohJakob** [comment]
@emmamarichal Yes, exactly. The instances do show up in the Affinity apps, but text is sometimes rendered incorrectly when using variable fonts (not limited to Figtree). I mainly use the variable fonts in Figma though, so I could use the Google Fonts version there, I guess.

**Comment by emmamarichal** [comment]
Ok I see :) So we'll have to wait until Affinity supports variable fonts hehe

**Comment by kenmcd** [comment]
Affinity supporting variable fonts is not going to help.
The problem is the instance names in the variable  font match the style names in the static font.
So the applications see them as duplicates.
Other applications also have problems with this.
Which is why commercial font developers as well as other FOSS font developers provide a differently named variable font.
Such as Inter does with Inter VF.
