### ISSUE TITLE
True Italics

### ISSUE THREAD

**Issue by arjpar** [erikdkennedy/figtree#46]
Would it be possible to develop true italics for this font, similar to Inter or Segoe UI?

**Comment by erikdkennedy** [comment]
The italics are hand-adjusted. One check to make sure they're displaying correctly: the italic 'a' is single story.

**Comment by arjpar** [comment]
Perhaps there was a misunderstanding. Currently the italics are obliques like Arial, I was wondering if the italics could be like Inter or Segoe UI which are true italics. Or am I wrong and the italics are already true italics?

**Comment by erikdkennedy** [comment]
They are true italics :)
