### ISSUE TITLE
Variable webfont version

### ISSUE THREAD

**Issue by IAmAdamTaylor** [erikdkennedy/figtree#9]
After downloading the code (great font btw!) I looked through the folders to see if there was a variable webfont version and couldn't find it.

I can see a Figtree.woff2 loading in the specimen site, would it be possible to make that available here as well please?

Or if I'm just not seeing something, please point me in the right direction :)

**Comment by erikdkennedy** [comment]
This is already a feature request on gftools, the Google Font tool that is used to build the font.
https://github.com/googlefonts/gftools/issues/350

**Comment by hernansartorio** [comment]
Hi, is this possible already? Not seeing any .woff2 variable version still.

P.S. Thank you for making this font!

**Comment by IAmAdamTaylor** [comment]
@hernansartorio If you install via Google Fonts that version will have the variable weights available.

**Comment by hernansartorio** [comment]
@IAmAdamTaylor thanks, although not sure if I'm seeing that. I'm looking to serve the file myself though, ended up converting the TTFs for now.

**Comment by erikdkennedy** [comment]
Hey @hernansartorio, @IAmAdamTaylor, good news! Variable WOFF2 works now 👍 

Grab it here:
https://github.com/erikdkennedy/figtree/tree/master/fonts/variable

**Comment by hernansartorio** [comment]
@erikdkennedy awesome, thank you!

P.S. If you want to see a little case study I’m using Figtree for everything in my new product: [pagy.co](https://pagy.co) :)
